### ISSUE TITLE
Multiple broken tests

### ISSUE THREAD

**Issue by bjh83** [google/lkml-gerrit-bridge#28]
Running all the tests

```
python3 archive_converter_test.py; python3 archive_updater_test.py; python3 main_test.py; python3 patch_parser_test.py
```

Causes the following failures:

```
.F.
======================================================================
FAIL: test_update_return_proper_patches (__main__.ArchiveConverterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "archive_converter_test.py", line 40, in test_update_return_proper_patches
    compare_message_subject(new_messages, subjects)
  File "archive_converter_test.py", line 30, in compare_message_subject
    self.assertEqual(message.subject, subject)
AssertionError: '[PATCH v2 2/4] kselftests/arm64: add nop checks for PAuth tests' != 'Re: [PATCH] Remove final reference to superfluous smp_commence().'
- [PATCH v2 2/4] kselftests/arm64: add nop checks for PAuth tests
+ Re: [PATCH] Remove final reference to superfluous smp_commence().


----------------------------------------------------------------------
Ran 3 tests in 0.009s

FAILED (failures=1)
.WARNING:absl:There are no commits in git repo: archive_path
......
----------------------------------------------------------------------
Ran 7 tests in 0.008s

OK
.FF
======================================================================
FAIL: test_server_upload_across_batches (__main__.MainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "main_test.py", line 70, in test_server_upload_across_batches
    mock_upload_messages.assert_called_with([messages[2].id,messages[3].id])
  File "/usr/lib/python3.8/unittest/mock.py", line 913, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: upload_messages(['<1169488670.15515.17.camel@earth>', '<20200831110450.30188-4-boyan.karatotev@arm.com>'])
Actual: upload_messages(['<20200827144112.v2.1.I6981f9a9f0c12e60f8038f3b574184f8ffc1b9b5@changeid>', '<20200831110450.30188-1-boyan.karatotev@arm.com>'])

======================================================================
FAIL: test_split_parent_and_reply_messages (__main__.MainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "main_test.py", line 51, in test_split_parent_and_reply_messages
    compare_message_subject(replies, expected_replies)
  File "main_test.py", line 49, in compare_message_subject
    self.assertEqual(message.subject, subject)
AssertionError: '[PATCH v2 2/4] kselftests/arm64: add nop checks for PAuth tests' != 'Re: [PATCH] Remove final reference to superfluous smp_commence().'
- [PATCH v2 2/4] kselftests/arm64: add nop checks for PAuth tests
+ Re: [PATCH] Remove final reference to superfluous smp_commence().


----------------------------------------------------------------------
Ran 3 tests in 0.010s

FAILED (failures=2)
...
----------------------------------------------------------------------
Ran 3 tests in 0.006s

OK
```

**Comment by dlatypov** [comment]
FYI, the tests haven't been clean since 178b618e8521.
At that commit, we have the first of the failures

```
AssertionError: '[PATCH v2 0/4] kselftests/arm64: add PAuth tests' != 'Re: [PATCH] Remove final reference to superfluous smp_commence().'
- [PATCH v2 0/4] kselftests/arm64: add PAuth tests
+ Re: [PATCH] Remove final reference to superfluous smp_commence().
```

**Comment by dlatypov** [comment]
That leaves the main_test.py failures.

I never got around to looking at the test since it always required a gerritcookies file, which I had ended up deleting at some point.

```
======================================================================
ERROR: test_server_upload_across_batches (__main__.MainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "main_test.py", line 68, in test_server_upload_across_batches
    server = Server()
  File "/usr/local/google/home/dlatypov/third_party/lkml-gerrit-bridge/src/main.py", line 44, in __init__
    rest = gerrit.get_gerrit_rest_api(COOKIE_JAR_PATH, GERRIT_URL)
  File "/usr/local/google/home/dlatypov/third_party/lkml-gerrit-bridge/src/gerrit.py", line 30, in get_gerrit_rest_api
    cookie_jar.load()
  File "/usr/lib/python3.8/http/cookiejar.py", line 1798, in load
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'gerritcookies'
```

The first failure is also due to non-determinism like in archive_converter_test.py, now fixed.

**Comment by dlatypov** [comment]
Ah, the `gerritcookies` issue is also affected by the move of the src code into `src`.

If you
* run from `src`, then it can't find `gerritcookies`
* run from `src/..`, then it can't find `./test_data`

Working around that by copying `gerritcookies` into `src`, I see the unit test is trying to actually clone the lore archive.

```
$ timeout 30 unshare -r -n python3 main_test.py
.Cloning into bare repository 'linux-kselftest/git/0.git'...
fatal: unable to access 'https://lore.kernel.org/linux-kselftest/0/': Could not resolve host: lore.kernel.org
...
subprocess.CalledProcessError: Command '['git', '-C', '..', 'clone', '--mirror', 'https://lore.kernel.org/linux-kselftest/0', 'linux-kselftest/git/0.git']' returned non-zero exit status 128.
```

Letting it do that, I see the failure you describe

```
Expected: upload_messages(['<20200831110450.30188-2-boyan.karatotev@arm.com>', '<20200831110450.30188-3-boyan.karatotev@arm.com>'])
Actual: upload_messages(['<20200831110450.30188-1-boyan.karatotev@arm.com>', '<20200827144112.v2.1.I6981f9a9f0c12e60f8038f3b574184f8ffc1b9b5@changeid>'])
```

**Comment by bjh83** [comment]
You fixed it, awesome! I was just sitting down to do that :smiley:

**Comment by dlatypov** [comment]
See commit desc of b897b4c08c0ae, there's still one more issue (trying to do `git clone`).
It'll just be adding a simple `mock.patch.object()` call, so I guess I'll go write that up and push in a bit.

**Comment by dlatypov** [comment]
Or nvm, it doesn't seem to be doing that anymore.

Guess that somehow got fixed along the way?
```
$ rm -rf linux-kselftest/
$ timeout 30 unshare -r -n python3 src/main_test.py
...
----------------------------------------------------------------------
Ran 3 tests in 0.009s

OK
```

**Comment by dlatypov** [comment]
Undo the nvm.
That's because I happened to have an old checkout of the archive at ".."

And apparently the `git clone` is just silently succeeded if the dir is already present even if it can't access the network (due to `unshare -r -n`)

4d5adb0c532a573a4e61cbf8da7a24c0cdd9410d should fix that, and now we're actually done.
